<?php

namespace Tetris\Numbers\Generator\Facebook;

use Tetris\Numbers\Generator\Shared\MetricFactory;

class FacebookMetricFactory extends MetricFactory
{
    protected $platform = 'Facebook';

    static function clear(array $config, $omittedKeys = []): array
    {
        return parent::clear($config, $omittedKeys); // TODO: Change the autogenerated stub
    }
}