<?php
return [
    "id" => "ctrsignificance",
    "property" => "CtrSignificance",
    "is_filter" => TRUE,
    "type" => "significancedata",
    "is_metric" => TRUE,
    "is_dimension" => FALSE,
    "is_percentage" => FALSE,
    "incompatible" => [
        "allconversionrate",
        "allconversionvalue",
        "allconversions",
        "averagepageviews",
        "averagetimeonsite",
        "bouncerate",
        "clickassistedconversionvalue",
        "clickassistedconversions",
        "clickassistedconversionsoverlastclickconversions",
        "clicktype",
        "contentimpressionshare",
        "contentranklostimpressionshare",
        "conversioncategoryname",
        "conversiontrackerid",
        "conversiontypename",
        "costperallconversion",
        "crossdeviceconversions",
        "impressionassistedconversionvalue",
        "impressionassistedconversions",
        "impressionassistedconversionsoverlastclickconversions",
        "numofflineimpressions",
        "numofflineinteractions",
        "offlineinteractionrate",
        "percentnewvisitors",
        "relativectr",
        "searchexactmatchimpressionshare",
        "searchimpressionshare",
        "searchranklostimpressionshare",
        "valueperallconversion"
    ]
];
