<?php
return [
    "id" => "externalconversionsource",
    "property" => "ExternalConversionSource",
    "is_filter" => TRUE,
    "type" => "externalconversionsource",
    "is_metric" => FALSE,
    "is_dimension" => TRUE,
    "is_percentage" => FALSE,
    "values" => [
        "UNKNOWN" => "Other",
        "WEBPAGE" => "Website",
        "ANALYTICS" => "Analytics",
        "UPLOAD" => "Import from clicks",
        "AD_CALL_METRICS" => "Calls from ads",
        "OFFERS" => "Offers",
        "ENGAGEMENT" => "Engagement ads",
        "WEBSITE_CALL_METRICS" => "Calls from website",
        "STORE_VISITS" => "Store visits",
        "ANDROID_IN_APP" => "Android in-app action",
        "ANDROID_DOWNLOAD" => "Android app install (from Google Play)",
        "IOS_IN_APP" => "iOS in-app action",
        "IOS_FIRST_OPEN" => "iOS app install (first open)",
        "APP_UNSPECIFIED" => "Mobile app",
        "ANDROID_FIRST_OPEN" => "Android app install (first open)",
        "UPLOAD_CALLS" => "Import from calls",
        "FIREBASE" => "Firebase",
        "CLICK_TO_CALL" => "Phone number clicks",
        "SALESFORCE" => "Salesforce.com",
        "STORE_SALES_CRM" => "Store sales (data partner)",
        "STORE_SALES_PAYMENT_NETWORK" => "Store sales (payment network)",
        "GOOGLE_PLAY" => "Google Play"
    ],
    "incompatible" => [
        "activeviewcpm",
        "activeviewctr",
        "activeviewimpressions",
        "activeviewmeasurability",
        "activeviewmeasurablecost",
        "activeviewmeasurableimpressions",
        "activeviewviewability",
        "averagecost",
        "averagecpc",
        "averagecpe",
        "averagecpm",
        "averagecpv",
        "clicks",
        "cost",
        "costperconversion",
        "ctr",
        "engagementrate",
        "engagements",
        "impressions",
        "interactionrate",
        "interactiontypes",
        "interactions",
        "valueperconversion",
        "videoviewrate",
        "videoviews"
    ]
];
