<?php
return [
    "id" => "conversiontrackerid",
    "property" => "ConversionTrackerId",
    "is_filter" => TRUE,
    "type" => "integer",
    "is_metric" => FALSE,
    "is_dimension" => TRUE,
    "is_percentage" => FALSE,
    "incompatible" => [
        "activeviewcpm",
        "activeviewctr",
        "activeviewimpressions",
        "activeviewmeasurability",
        "activeviewmeasurablecost",
        "activeviewmeasurableimpressions",
        "activeviewviewability",
        "averagecost",
        "averagecpc",
        "averagecpe",
        "averagecpm",
        "averagecpv",
        "averagefrequency",
        "averagepageviews",
        "averageposition",
        "averagetimeonsite",
        "bouncerate",
        "clickassistedconversionvalue",
        "clickassistedconversions",
        "clickassistedconversionsoverlastclickconversions",
        "clicks",
        "contentbudgetlostimpressionshare",
        "contentimpressionshare",
        "contentranklostimpressionshare",
        "cost",
        "ctr",
        "engagementrate",
        "engagements",
        "gmailforwards",
        "gmailsaves",
        "gmailsecondaryclicks",
        "impressionassistedconversionvalue",
        "impressionassistedconversions",
        "impressionassistedconversionsoverlastclickconversions",
        "impressionreach",
        "impressions",
        "interactionrate",
        "interactiontypes",
        "interactions",
        "invalidclickrate",
        "invalidclicks",
        "numofflineimpressions",
        "numofflineinteractions",
        "offlineinteractionrate",
        "percentnewvisitors",
        "relativectr",
        "searchbudgetlostimpressionshare",
        "searchexactmatchimpressionshare",
        "searchimpressionshare",
        "searchranklostimpressionshare",
        "videoquartile100rate",
        "videoquartile25rate",
        "videoquartile50rate",
        "videoquartile75rate",
        "videoviewrate",
        "videoviews"
    ],
    "parse" => function ($data): int {
        return intval(str_replace(',', '', $data->{'ConversionTrackerId'}));
    }
];
