<?php
return [
    "id" => "slot",
    "property" => "Slot",
    "is_filter" => TRUE,
    "type" => "slot",
    "is_metric" => FALSE,
    "is_dimension" => TRUE,
    "is_percentage" => FALSE,
    "values" => [
        "SearchRhs" => "Google search: Side",
        "SearchTop" => "Google search: Top",
        "SearchOther" => "Google search: Other",
        "Content" => "Google Display Network",
        "AfsTop" => "Search partners: Top",
        "AfsOther" => "Search partners: Other",
        "Unknown" => ""
    ],
    "incompatible" => [
        "allconversionrate",
        "allconversionvalue",
        "allconversions",
        "averagefrequency",
        "averagepageviews",
        "averagetimeonsite",
        "bouncerate",
        "clickassistedconversionvalue",
        "clickassistedconversions",
        "clickassistedconversionsoverlastclickconversions",
        "contentbudgetlostimpressionshare",
        "contentimpressionshare",
        "contentranklostimpressionshare",
        "costperallconversion",
        "crossdeviceconversions",
        "hourofday",
        "impressionassistedconversionvalue",
        "impressionassistedconversions",
        "impressionassistedconversionsoverlastclickconversions",
        "impressionreach",
        "invalidclickrate",
        "invalidclicks",
        "numofflineimpressions",
        "numofflineinteractions",
        "offlineinteractionrate",
        "percentnewvisitors",
        "relativectr",
        "searchbudgetlostimpressionshare",
        "searchexactmatchimpressionshare",
        "searchimpressionshare",
        "searchranklostimpressionshare",
        "valueperallconversion"
    ]
];
