<?php
return [
    "id" => "conversioncategoryname",
    "property" => "ConversionCategoryName",
    "is_filter" => TRUE,
    "type" => "string",
    "is_metric" => FALSE,
    "is_dimension" => TRUE,
    "is_percentage" => FALSE,
    "incompatible" => [
        "activeviewcpm",
        "activeviewctr",
        "activeviewimpressions",
        "activeviewmeasurability",
        "activeviewmeasurablecost",
        "activeviewmeasurableimpressions",
        "activeviewviewability",
        "averagecost",
        "averagecpc",
        "averagecpe",
        "averagecpm",
        "averagecpv",
        "averagepageviews",
        "averageposition",
        "averagetimeonsite",
        "bouncerate",
        "clickassistedconversionvalue",
        "clickassistedconversions",
        "clickassistedconversionsoverlastclickconversions",
        "clicks",
        "cost",
        "ctr",
        "engagementrate",
        "engagements",
        "gmailforwards",
        "gmailsaves",
        "gmailsecondaryclicks",
        "impressionassistedconversionvalue",
        "impressionassistedconversions",
        "impressionassistedconversionsoverlastclickconversions",
        "impressions",
        "interactionrate",
        "interactiontypes",
        "interactions",
        "percentnewvisitors",
        "searchexactmatchimpressionshare",
        "searchimpressionshare",
        "searchranklostimpressionshare",
        "videoquartile100rate",
        "videoquartile25rate",
        "videoquartile50rate",
        "videoquartile75rate",
        "videoviewrate",
        "videoviews"
    ]
];
